### PR TITLE
course up to date

### PR DESCRIPTION
**Pull request by dmurawsky**
Looks like you updated the course already 👍 

Thanks by the way, this course is just what I needed!

### CODE REVIEW

**Comment by Luis-Palacios** [comment]
I can confirm the course is up to date

https://github.com/joeeames/WebpackFundamentalsCourse/issues/8

**Comment by joeeames** [comment]
I'm not sure why you would say this. Babel is on a new major version. This course uses the last version.

I'm going to be updating the course here soon, but I don't know if I'm willing to mark it as "up to date". What makes you say that it is?

**Comment by dmurawsky** [comment]
👍  Thanks for all your hard work, educating nubs like me @joeeames 
Between Pluralsight and Podcasts, I've probably spent more time listening to you over the past 12 months, than my wife. Just don't tell my wife 😉

**Comment by arshdkhn1** [comment]
@joeeames Thanks, I havent watched the course yet but 

> I can confirm the course is up to date

made me add it to my watch list.

**Pull request merged**
